### PR TITLE
Adding versioning for logfilter

### PR DESCRIPTION
**Pull request by yolandeleungFT**
splunkhttpforwarder version to be updated.

### CODE REVIEW

**Comment by jussi-ft** [comment]
Looks good!

**Comment by jussi-ft** [comment]
Happy days, all good!

**Comment by jussi-ft** [comment]
Please update splunk-forwarder version to v0.0.5.
Branch has been merged to master.
Thanks,
jussi

**Comment by yolandeleungFT** [comment]
superceded

**Pull request closed without merging**
