### PR TITLE
Using dynamic container names

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by martingartonft** [comment]
That's a pretty neat workaround.

+1

**Comment by catalin-ilea** [comment]
This does mean we have to change all the service files. I guess it's better than waiting around for this to be fixed upstream.

**Comment by martingartonft** [comment]
maybe do this one and see how it pans out for a while, meanwhile I'll push more on the docker ticket or "stare at the source code" to see what that achieves.

**Comment by tamas-molnar** [comment]
+1

**Comment by tamas-molnar** [comment]
Superseded by https://github.com/Financial-Times/pub-service-files/pull/17

**Pull request closed without merging**
